package alexndr.plugins.synergy;

import java.util.List;

import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import com.google.common.collect.Lists;

/**
 * @author AleXndrTheGr8st
 */
public class ModInfo {
	public static final String ID = "synergy";
	public static final String NAME = "Synergy";
	public static final String VERSION = "0.0.1";
	public static final String DESCRIPTION = "A new plugin for Minecraft. Adds new ores, materials and mechanics.";
	public static final String URL = "http://bit.ly/SimpleOres";
	public static final List<String> AUTHORS = Lists.newArrayList("AleXndrTheGr8st");
	public static final String CREDITS = "Created by AleXndrTheGr8st.";
	public static final String LOGO = "/assets/simplecore/logos/SimpleOres.png";
	public static final String PARENT = "";
	
	public static final boolean USEDEPENDENCYINFO = true;
	public static final String VERSIONURL = "https://dl.dropboxusercontent.com/u/66466201/Mods/SimpleOres%202/SimpleOres%202%20Version.txt";

	public static void setModInfoProperties(FMLPreInitializationEvent event) {
		event.getModMetadata().autogenerated = false;
		event.getModMetadata().modId = ID;
		event.getModMetadata().name = NAME;
		event.getModMetadata().description = DESCRIPTION;
		event.getModMetadata().version = VERSION;
		event.getModMetadata().url = URL;
		event.getModMetadata().authorList = AUTHORS;
		event.getModMetadata().credits = CREDITS;
		event.getModMetadata().logoFile = LOGO;
		event.getModMetadata().parent = PARENT;
		event.getModMetadata().useDependencyInformation = USEDEPENDENCYINFO;
	}
}
